[package]
name = "dod_hwauth"
version = "0.1.0"
authors = ["Jeffrey McAteer <jeffrey.p.mcateer@gmail.com>"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
# LibC gives us the widths of all C data types
libc = "0.2.90"
# pcsc gives us smartcard library access across Windows, Linux, and MacOS
pcsc = "2.4"

